finally block gets executed irrespective of whether exception is raised or not.
it can be used to release resources such as file,socket,database connection etc. since you can not rely upon "finalized" method for the same task.

finally block can follow after catch (try..catch...finally ) or even after try (try...finally).

finally block will not get executed if

a) System.exit(0) is called inside try ,catch or finally block.

b) exception gets raised in finally block itself.